# **__Python Homework (NumPy, Pandas)__**

## 1. What does *Pandas* stand for?
- Python Data Analysis Library

---

# 2. What are the 2 collections used in *Pandas*?**
- Series: One-dimensional labeled array 
- DataFrame: Two-dimensional labeled data structure (e.g. table) 

---

# 3. Name 4 things *Pandas* can do for us.
1. Data Cleaning
2. Data manipulation
3. Data Aggregation
4. Data Exporting

---

# 4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
- inplace=true

---

# 5. What is a *CSV*?
- *Comma-Separated Values*

---

# 6. When cleaning data what values do we not like in our data?
- Missing values
- Duplicates
- Outliers
- Inconsistent Formats

---

In [14]:
# 7  Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2).
# You can use the reshape method -- .reshape()

import numpy as np

# Create an array with shape (2, 3, 2)
array = np.array([
    [[1, 2], [3, 4], [5, 6]],  # Block 1
    [[7, 8], [9, 10], [11, 12]]  # Block 2
])

print("Array:")
print(array)
print("\nShape:", array.shape)


Array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Shape: (2, 3, 2)


In [13]:
# Reshape array

reshaped_array = array.reshape(3, 2, 2)

print("Original Array (1D):")
print(array)

print("\nReshaped Array (3, 2, 2):")
print(reshaped_array)

print("\nShape of Reshaped Array:", reshaped_array.shape)


Original Array (1D):
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Reshaped Array (3, 2, 2):
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

Shape of Reshaped Array: (3, 2, 2)


In [5]:
# 8 Use NumPy linspace to create an array with 6 linearly spaced values between 0 and 20

import numpy as np

linspace_array = np.linspace(0, 20, 6)
print("\nLinearly spaced array:")
print(linspace_array)


Linearly spaced array:
[ 0.  4.  8. 12. 16. 20.]


In [6]:
# Make a Deep Copy of the above array

linspace_array = np.linspace(0, 20, 6)
deep_copy_array = linspace_array.copy()

print("\nLinearly spaced array:")
print(linspace_array)

print("\nDeep copy of the array:")
print(deep_copy_array)



Linearly spaced array:
[ 0.  4.  8. 12. 16. 20.]

Deep copy of the array:
[ 0.  4.  8. 12. 16. 20.]


In [7]:
# Concatenate these 3 arrays into a new array named 'newArray'...

import numpy as np

# Define the arrays
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

# Concatenate the arrays along axis 0 (rows)
newArray = np.concatenate((array1, array2, array3), axis=0)

print("Concatenated array (newArray):")
print(newArray)


Concatenated array (newArray):
[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [12]:
# 11 Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray, axis=1)

print("Original array (newArray):")
print(newArray)

print("\nSorted array (sortedArray):")
print(sortedArray)

Original array (newArray):
[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

Sorted array (sortedArray):
[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [11]:
# Testing flatten array and sort

sortedArray = np.sort(newArray, axis=None)

print("Original array (newArray):")
print(newArray)

print("\nSorted array (sortedArray):")
print(sortedArray)

Original array (newArray):
[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

Sorted array (sortedArray):
[ 2  4  5  6  7 11 11 12 13 16 25 81]


In [14]:
#12 Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

tuple1, tuple2, tuple3, tuple4 = newArray[:2], newArray[2:4], newArray[4:6], newArray[6:]

# Print the variables
print("Tuple 1:", tuple1)
print("Tuple 2:", tuple2)
print("Tuple 3:", tuple3)
print("Tuple 4:", tuple4)

Tuple 1: [[25 16]
 [11  2]]
Tuple 2: [[13  4]
 [ 7 81]]
Tuple 3: [[ 5  6]
 [11 12]]
Tuple 4: []


In [16]:
# 13 Combined and sort the following arrays into one called 'comboArray' ...

import numpy as np

# Define arrays
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

# Combine using np.concatenate
comboArray = np.concatenate((one, two, three))

# Sort the combined array
comboArray = np.sort(comboArray)

# Print the resulting array
print("Combined and sorted array (comboArray):")
print(comboArray)

Combined and sorted array (comboArray):
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [17]:
import numpy as np

# Use comboArray from above

# Slicing activities
sec1 = comboArray[1]  # The 2nd element
sec2 = comboArray[2:]  # All elements from the 3rd element to the last
sec3 = comboArray[3:14]  # All elements from the 4th to the 14th elements
sec4 = comboArray[-6:]  # The last 6 elements
sec5 = comboArray[:-8]  # All elements from #0 up to and including #15 (negative indexing)
sec6 = comboArray[20::2]  # From #20 every even element to the end
sec7 = comboArray[::-5]  # From the last element moving forward, every 5th element

# Print results
print("sec1 - the 2nd element:", sec1)
print("sec2 - all elements from the 3rd element to the last:", sec2)
print("sec3 - all elements from the 4th to the 14th elements:", sec3)
print("sec4 - the last 6 elements:", sec4)
print("sec5 - all elements from #0 up to and including #15 (negative method):", sec5)
print("sec6 - from #20 every even element to the end:", sec6)
print("sec7 - from the last element moving forward, every 5th element:", sec7)


sec1 - the 2nd element: 1
sec2 - all elements from the 3rd element to the last: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3 - all elements from the 4th to the 14th elements: [ 3  4  5  6  7 10 11 12 13 14 15]
sec4 - the last 6 elements: [22 23 24 25 26 27]
sec5 - all elements from #0 up to and including #15 (negative method): [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17]
sec6 - from #20 every even element to the end: [24 26]
sec7 - from the last element moving forward, every 5th element: [27 22 15 10  3]


In [1]:
import pandas as pd

# Create the Series for each column
ingredients = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name='Ingredients')
quantity = pd.Series([4, 1, 2, 1], name='Quantity')
unit = pd.Series(['cups', 'cup', 'large', 'can'], name='Unit')

# Combine the Series into a DataFrame
df = pd.DataFrame({
    'Ingredients': ingredients,
    'Quantity': quantity,
    'Unit': unit
})

# Assign a name to the Series (optional for indexing context)
df.index.name = 'Dinner'

print(df)


       Ingredients  Quantity   Unit
Dinner                             
0            Flour         4   cups
1             Milk         1    cup
2             Eggs         2  large
3             Spam         1    can


In [2]:
#16 Take this data and create a DataFrame named studentData

import pandas as pd

# Define the dictionary
data = {
    'Name': ['Jai', 'Janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

# Create the DataFrame
studentData = pd.DataFrame(data)

# Display the DataFrame
print(studentData)


      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  Janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [3]:
#17 Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

# Define the desserts list
desserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

# Add the new column to the DataFrame
studentData['Dessert'] = desserts

print(studentData)



      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  Janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Dessert  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [4]:
#18 Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

# Sort the DataFrame by 'Name' and then by 'address'
sorted_studentData = studentData.sort_values(by=['Name', 'address'], ascending=[True, True])

print(sorted_studentData)


      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  Janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Dessert  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge  


In [5]:
#19 Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

import pandas as pd

# Create the DataFrame
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

# Save the DataFrame to a CSV file
df.to_csv('cows_and_goats.csv')

print("The DataFrame has been saved as 'cows_and_goats.csv'")


The DataFrame has been saved as 'cows_and_goats.csv'


In [6]:
#20 (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

import pandas as pd

# (A) Create the initial DataFrame and save it as a .CSV file
vegetables_data = {
    'Vegetable': ['Tomatoes', 'Onions', 'Lettuce', 'Green Onions'],
    'Quantity': [10, 5, 1, 5],
    'Price': [2.99, 3.99, 2.49, 4.50]
}
vegetables_df = pd.DataFrame(vegetables_data)
vegetables_df.to_csv('vegetables.csv', index=False) 

# (B) Modify the DataFrame: Add Potatoes and update Lettuce quantity
vegetables_df.loc[len(vegetables_df)] = ['Potatoes', 8, 7.50]  # Add Potatoes
vegetables_df.loc[vegetables_df['Vegetable'] == 'Lettuce', 'Quantity'] = 2  # Update Lettuce quantity

# Save the updated DataFrame as a new .CSV file
vegetables_df.to_csv('vegetables_updated.csv', index=False)  # Save as vegetables_updated.csv

print("Files saved: vegetables.csv and vegetables_updated.csv")


Files saved: vegetables.csv and vegetables_updated.csv


In [7]:
# Load the CSV file
file_path = 'vegetables.csv'  
df = pd.read_csv(file_path)

# Display the contents
print(df)

      Vegetable  Quantity  Price
0      Tomatoes        10   2.99
1        Onions         5   3.99
2       Lettuce         1   2.49
3  Green Onions         5   4.50


In [8]:
# Load the updated CSV file
file_path1 = 'vegetables_updated.csv'  
df = pd.read_csv(file_path1)

# Display the contents
print(df)

      Vegetable  Quantity  Price
0      Tomatoes        10   2.99
1        Onions         5   3.99
2       Lettuce         2   2.49
3  Green Onions         5   4.50
4      Potatoes         8   7.50
